### ISSUE TITLE
Mockups for Admin panel UI

### ISSUE THREAD

**Issue by XE-Cute** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#1]

**Comment by evanderaimufua** [comment]
not sure how i can commit figma designs:
click on admin page and you should see the mockups 
https://www.figma.com/file/JKxRRE9YYOCVaJPBPR3T3E/Casi-mockup?type=design&node-id=0%3A1&mode=design&t=BHvyjFTrwoLiP1Dw-1

**Comment by kurtp21** [comment]
The mockups are great, I'm pretty sure Dr. Epp will approve of them.
