### ISSUE TITLE
Complete Frontend Design For App

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#2]
Complete the program design framework as soon as possible. 

Will consideration of our stakeholder's design choices:
- Simplistic style like Survey Monkey
- Takes design styles from both Evander's and Princess' design mock-ups (shown during first meeting with stake holder)

**Comment by evanderaimufua** [comment]
https://www.figma.com/file/JKxRRE9YYOCVaJPBPR3T3E/Casi-mockup?type=design&node-id=0-1&mode=design&t=8PEQFTIzQZwWH10u-0
not sure how to commit these to get reviewed so just gonna comment. theres a side nav bar , mock up for notifications page, adjusted sign up flow for requesting id and terms & conditions etc

**Comment by kurtp21** [comment]
I reviewed them and they are great! We now have a reference for the UI for our application.
