### ISSUE TITLE
Front-end Setup

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#22]
Set up the frontend with the bare minimum things and test to make sure it works. 

Example:
- Output "Hello, World" onto the app screen

**Comment by KhoaNguyen178** [comment]
I set it up on the front-end-setup branch, as well as a README file to show the team how to run it (may make a script to auto install everything, but i'm not too familiar with that, will take a look tho). Let me know if you have any trouble running the program.

**Comment by Leo-YiLuan** [comment]
I have dockerized the frontend. Now, we need clear documentation on how to use Docker to run the frontend. Build-master will have our documentation ready by ID1.

**Comment by Leo-YiLuan** [comment]
> I have applied the Dockerization solution found by our build-master to the front-end setup. Now, we need clear documentation on how to use Docker to run the frontend. The build-master will have our documentation ready by ID1. _Test with Expo go on both iOS and Android._

The documentation for dockerization has been added.

**Comment by kurtp21** [comment]
This issue needs to be refactored since our requirements changed from a desktop AND mobile app to just a web app.
