### ISSUE TITLE
Back-end Setup

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#23]
Set up the backend with Node JS and Express JS in TypeScript. Then make sure you test it to see if it works.

Example:
- Test with "Hello, World"

**Comment by kurtp21** [comment]
Have this been completed or is it still in the works?

**Comment by thaiVL** [comment]
> Have this been completed or is it still in the works?

It's been completed, but just need some minor refactoring.

**Comment by kurtp21** [comment]
Awesome, that's good to hear!
